### ISSUE TITLE
hi! mind if i use your code?

### ISSUE THREAD

**Issue by Wilker-uwu** [SeyfullahGundogdu/multi-feature-gradient-descent#1]
i'm bad at math and i've been looking for a code from someone who's done math so i can use it in my project that uses math. i'm asking this because the repo doesn't have a license file attached to it.

thank you for the attention ^^

**Comment by SeyfullahGundogdu** [comment]
Yeah, go ahead. No problem. Thanks by the way I didn't notice there was no licence. I added GPL v3 as the licence.

**Comment by Wilker-uwu** [comment]
thank _you_ for making this in the first place :3
